DROP TABLE
    IF EXISTS NYC_BARS;
DROP TABLE
    IF EXISTS NYC_ZIPS;
CREATE TABLE
    NYC_ZIPS
    (
        ZIP VARCHAR(255) NOT NULL,
        NEIGHBORHOOD VARCHAR(255) DEFAULT NULL,
        POPULATION INTEGER DEFAULT NULL,
        DENSITY REAL DEFAULT NULL,
        INCOME DECIMAL(20, 2) DEFAULT NULL,
        MALE REAL DEFAULT NULL,
        FEMALE REAL DEFAULT NULL,
        UNMARRIED REAL DEFAULT NULL,
        MARRIED REAL DEFAULT NULL,
        SEPARATED REAL DEFAULT NULL,
        WIDOWED REAL DEFAULT NULL,
        DIVORCED REAL DEFAULT NULL,
        CONSTRAINT ZIP_UNIQUE UNIQUE (ZIP)
    );
CREATE TABLE
    NYC_BARS
    (
        ID VARCHAR(255) NOT NULL,
        NAME VARCHAR(255) DEFAULT NULL,
        ADDRESS VARCHAR(255) DEFAULT NULL,
        ADDRESS_EXTENDED VARCHAR(255) DEFAULT NULL,
        CITY VARCHAR(255) DEFAULT NULL,
        STATE VARCHAR(255) DEFAULT NULL,
        ZIP VARCHAR(255) DEFAULT NULL,
        TEL VARCHAR(255) DEFAULT NULL,
        LATITUDE REAL DEFAULT NULL,
        LONGITUDE REAL DEFAULT NULL,
        WEBSITE VARCHAR(255) DEFAULT NULL,
        CATEGORY VARCHAR(255) DEFAULT NULL,
        CUISINE VARCHAR(255) DEFAULT NULL,
        PRICE REAL DEFAULT NULL,
        RATING REAL DEFAULT NULL,
        WIFI BOOLEAN DEFAULT NULL,
        CONSTRAINT NYC_BARS_ID_UNIQUE UNIQUE (ID),
        FOREIGN KEY(ZIP) REFERENCES NYC_ZIPS(ZIP)
    );